'use strict';

const { h } = require('jsx-node');

module.exports = ({ link, site, user }) => (
  <table align="center" width="600">
    <tr>
      <td style="text-align: center; font-family: Arial, sans-serif;" valign="top">
        <h1>Hello</h1>
        <p>You have almost completed your registration process! All you need to do now
        is click on the link below to verify your email address.</p>

        <p><a href={link}>{link}</a></p>

        <p>This link will only be active for 48 hours.</p>

        <p><strong>This email is autogenerated and cannot be replied to.</strong></p>
      </td>
    </tr>
  </table>
);
